(define (problem knights-tour-problem-v2)
    (:domain knights-tour-v2)

    (:objects
        n1 n2 n3 n4 n5 n6 n7 n8
    )

    (:init
        (at n1 n8)
        (visited n1 n8)
        (diff-by-one n1 n2)
        (diff-by-one n2 n1)
        (diff-by-one n2 n3)
        (diff-by-one n3 n2)
        (diff-by-one n3 n4)
        (diff-by-one n4 n3)
        (diff-by-one n4 n5)
        (diff-by-one n5 n4)
        (diff-by-one n5 n6)
        (diff-by-one n6 n5)
        (diff-by-one n6 n7)
        (diff-by-one n7 n6)
        (diff-by-one n7 n8)
        (diff-by-one n8 n7)

        (diff-by-two n1 n3)
        (diff-by-two n3 n1)
        (diff-by-two n2 n4)
        (diff-by-two n4 n2)
        (diff-by-two n3 n5)
        (diff-by-two n5 n3)
        (diff-by-two n4 n6)
        (diff-by-two n6 n4)
        (diff-by-two n5 n7)
        (diff-by-two n7 n5)
        (diff-by-two n6 n8)
        (diff-by-two n8 n6)
    )

    (:goal
        (and(visited n1 n1)
            (visited n1 n2)
            (visited n1 n3)
            (visited n1 n4)
            (visited n1 n5)
            (visited n1 n6)
            (visited n1 n7)
            (visited n1 n8)
            (visited n2 n1)
            (visited n2 n2)
            (visited n2 n3)
            (visited n2 n4)
            (visited n2 n5)
            (visited n2 n6)
            (visited n2 n7)
            (visited n2 n8)
            (visited n3 n1)
            (visited n3 n2)
            (visited n3 n3)
            (visited n3 n4)
            (visited n3 n5)
            (visited n3 n6)
            (visited n3 n7)
            (visited n3 n8)
            (visited n4 n1)
            (visited n4 n2)
            (visited n4 n3)
            (visited n4 n4)
            (visited n4 n5)
            (visited n4 n6)
            (visited n4 n7)
            (visited n4 n8)
            (visited n5 n1)
            (visited n5 n2)
            (visited n5 n3)
            (visited n5 n4)
            (visited n5 n5)
            (visited n5 n6)
            (visited n5 n7)
            (visited n5 n8)
            (visited n6 n1)
            (visited n6 n2)
            (visited n6 n3)
            (visited n6 n4)
            (visited n6 n5)
            (visited n6 n6)
            (visited n6 n7)
            (visited n6 n8)
            (visited n7 n1)
            (visited n7 n2)
            (visited n7 n3)
            (visited n7 n4)
            (visited n7 n5)
            (visited n7 n6)
            (visited n7 n7)
            (visited n7 n8)
            (visited n8 n1)
            (visited n8 n2)
            (visited n8 n3)
            (visited n8 n4)
            (visited n8 n5)
            (visited n8 n6)
            (visited n8 n7)
            (visited n8 n8))
    )

)