(define (problem linehaul-with-costs-p01)
    (:domain linehaul-with-costs)

    (:objects
        ADoubleRef - refrigerated_truck
        BDouble - truck
        depot GV E BW - location
        n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12 n13 n14 n15 n16 n17 n18 n19 n20 - quantity
    )

    (:init
        (at ADoubleRef depot)
        (at BDouble depot)
        (free_capacity ADoubleRef n19)
        (free_capacity BDouble n14)
        (demand_chilled_goods GV n18)
        (demand_ambient_goods GV n12)
        (demand_chilled_goods E n7)
        (demand_ambient_goods E n2)
        (demand_chilled_goods BW n3)
        (demand_ambient_goods BW n0)
        (plus1 n0 n1)
        (plus1 n1 n2)
        (plus1 n2 n3)
        (plus1 n3 n4)
        (plus1 n4 n5)
        (plus1 n5 n6)
        (plus1 n6 n7)
        (plus1 n7 n8)
        (plus1 n8 n9)
        (plus1 n9 n10)
        (plus1 n10 n11)
        (plus1 n11 n12)
        (plus1 n12 n13)
        (plus1 n13 n14)
        (plus1 n14 n15)
        (plus1 n15 n16)
        (plus1 n16 n17)
        (plus1 n17 n18)
        (plus1 n18 n19)
        (plus1 n19 n20)

        (= (distance depot GV) 573)
        (= (distance depot E) 896)
        (= (distance depot BW) 876)
        (= (distance GV depot) 573)
        (= (distance GV E) 372)
        (= (distance GV BW) 296)
        (= (distance E depot) 896)
        (= (distance E GV) 372)
        (= (distance E BW) 79)
        (= (distance BW depot) 876)
        (= (distance BW GV) 296)
        (= (distance BW E) 79)

        (= (cost_per_km ADoubleRef) 3.04)
        (= (cost_per_km BDouble) 2.59)

        (= (total_cost) 0)
    )
    (:goal
        (and (demand_chilled_goods GV n0)
            (demand_ambient_goods GV n0)
            (demand_chilled_goods E n0)
            (demand_ambient_goods E n0)
            (demand_chilled_goods BW n0)
            (demand_ambient_goods BW n0)
            (at ADoubleRef depot)
            (at BDouble depot))
    )

    (:metric minimize
        (total_cost)
    )
)