userInput=true
fogOfWar=true
autoCamera=false
chaosLauncherPath =Chaoslauncher
speed=50
showResources=false
map.drawIDs=true
map.drawPings=false
map.drawPlayerUnits=true
map.drawEnemyUnits=true
map.drawNeutralUnits=true
map.drawResources=true
map.drawStartSpots=true
map.drawRegions=false
map.drawAreas=true
map.fillRegions=false
map.drawChokepoints=true
behaviorTree.scrollToExecutingNode=true
