GameSettings.IgnoreBases=true
GameSettings.ShowGUI=true
GameSettings.AutoRestart=false
GameSettings.UseManners=false
GameSettings.Fastest=true
GameSettings.UserInput=true
GameSettings.QuitOnGameEnd=false
GameSettings.AutoCamera=false
GameSettings.fogOfWar=true
GameSettings.chaosLauncherPath =Chaoslauncher
GameSettings.speed=50
GameSettings.map.drawIDs=true
GameSettings.map.drawPings=false
GameSettings.map.drawPlayerUnits=true
GameSettings.map.drawEnemyUnits=true
GameSettings.map.drawNeutralUnits=true
GameSettings.map.drawResources=true
GameSettings.map.drawStartSpots=true
GameSettings.map.drawRegions=true
GameSettings.map.fillRegions=false
GameSettings.map.drawChokepoints=true

BehaviorTree.scrollToExecutingNode=true
BehaviorTree.pauseBehaviorTree=true
BehaviorTree.showResources=false
